logout-done
esskew213/lunchgowhere-frontend pull request #14
Opened 2022-04-11 07:53 UTC by EnixYY

Logout can delete the token already.

Also did up some CSS for the landing page.

2022-04-11 10:15 UTC, esskew213 requested changes

2022-04-11 10:15 UTC, esskew213 commented on lunch-go-where/src/pages/Home.js
> +    useEffect(() => {
can you protect the home page as we discussed? you can look inside the `Result` component, just copy and paste the code from there, i.e.:
`apis.checkAuthUser().then((res) => {console.log(res)}).catch((err) => {
					console.log(err.response);
					navigate("/");
				});`
				
you'll need to make sure `jwtAuth` is protecting the backend route (should be in `routes/user` too. Let me know if you have questions about this!

2022-04-11 10:15 UTC, esskew213 commented on lunch-go-where/src/pages/Home.js
> +                    ? recStalls.map((stall) => {
as mentioned just now, to remove that error _"Warning: Each child in a list should have a unique "key" prop.", can you map using `recStalls.map((stall, idx) => { return ( <IndividualCard key={idx} nameOfStall={stall.stallName}... ) }`

2022-04-11 10:15 UTC, esskew213 commented on lunch-go-where/src/pages/Home.js
> +                                      // img={stall.img}
Correct me if i'm wrong but img isn't displaying correctly atm. We need to make sure the image field is populated first on the backend so that the image displays properly. Sp 1) use .populate("img", { url: 1 }) in the backend, then in the frontend, change it to `img={stall.img.url}`

I think you may also find that back in the card component, you may need to constrain the width of the card to a fixed value e.g. 300px, and the height of the image, because people may be uploading images of diff size and dimensions.

2022-04-11 10:15 UTC, esskew213 commented on lunch-go-where/src/pages/Home.js
> +                                  />
Similar to the image, it looks like the location is only displaying an ID at the moment, not the hawker center name. Can you see if it works if you: 1) use `.populate('location')` on the backend, and then pass in `stall.location.centerName` on the front?

2022-04-11 12:59 UTC, EnixYY commented on lunch-go-where/src/pages/Home.js
> +    useEffect(() => {
I have placed the auth checks on the home page and also the new stall page. Have tested it and it will only be available if we have the token.

2022-04-11 13:04 UTC, EnixYY commented on lunch-go-where/src/pages/Home.js
> +                    ? recStalls.map((stall) => {
Unique key had been updated as per above and error is solved. Thank you sarah! :D

2022-04-11 14:47 UTC, EnixYY commented on lunch-go-where/src/pages/Home.js
> +                                      // img={stall.img}
Yay location and Image is settled too

2022-04-12 02:10 UTC, esskew213 approved these changes
Yay!

2022-04-12 02:10 UTC, merged